### ISSUE TITLE
Screen version missmatch

### ISSUE THREAD

**Issue by sippi2577** [rommulaner/Anycubic_Vyper_MB_CE_6.2#17]
Hallo, since Update 6.2 there is a warning messege on the screen and the light keeps flashing.

"Please flash your TFT screen: version missmatch - build 61 found but expected 62"

6.1 works fine.

**Comment by rommulaner** [comment]
Sure, because you need to flash the screen to 6.2.

**Comment by sippi2577** [comment]
of course i couldn`t find the file until now..... 

I am so sorry for the inconvenience.
