### ISSUE TITLE
Calibrating stuck on preheat

### ISSUE THREAD

**Issue by Mootfrost777** [rommulaner/Anycubic_Vyper_MB_CE_6.2#18]
With esteps Hotend heats to 190 and starts heating up and down +- 3degrees but doing no calibration. reboot required.
With leveling it heats, touches surface then says that calibration complete and values(zeros) stored.
 What am I doing wrong?

**Comment by rommulaner** [comment]
Do a PID calibration before anything else. If the temperature cannot be hold stable, leveling, extruding and probing doesn't work as expected.

**Comment by Mootfrost777** [comment]
> Прежде всего выполните калибровку ПИД-регулятора. Если температуру невозможно поддерживать стабильной, выравнивание, выдавливание и зондирование не работают должным образом.

Thank you sou much for the advice, esteppers passed. But bed leveling still starts and immediately ends without doing anything

**Comment by rommulaner** [comment]
Perhaps the nozzle is too high and it runs to the set limit of -3mm and that's why it's aborting the leveling.
I had currently one with a similar problem and I will change that in a new built today. I will inform you when it's available.

**Comment by rommulaner** [comment]
6.2.1-2 is now available for Mainboard please test with that version. Display has not changed.

**Comment by Mootfrost777** [comment]
It works! Thank you for your help.
