### ISSUE TITLE
The Y damping in the menu overwrites the X damping. It also overwrites the console commands

### ISSUE THREAD

**Issue by ciobz** [rommulaner/Anycubic_Vyper_MB_CE_6.2#24]

**Comment by rommulaner** [comment]
Thank you for that! There was a mistake in the code at X damping.
Fixed in 6.2.1-4

**Comment by ciobz** [comment]
Do I need to reflash my MB to get the update? If yes do i lose my settings?
Sorry if the question is dumb i just follow guides.

**Comment by ciobz** [comment]
Thanks for the advice and the firmware!
