### ISSUE TITLE
Please stop linking to CR6 Discord

### ISSUE THREAD

**Issue by Thinkersbluff** [rommulaner/Anycubic_Vyper_MB_CE_6.2#26]
When your users run into difficulties with your firmware they are following your ReadMe links to the CR6 Community Discord. 

We do not support your firmware. It just creates confusion and disruption to send them to us. 

Please remove those links.

**Comment by rommulaner** [comment]
Sure no problem. I never edited the text because it already was the Vyper CE.

**Comment by Thinkersbluff** [comment]
This link is part of the problem:

"We have our own Discord server"

If you indeed have your own Discord, please fix the link, else please delete that text and link.
