### ISSUE TITLE
Anycubic Vyper reboots after 15 minutes of printing 

### ISSUE THREAD

**Issue by Gman1988** [rommulaner/Anycubic_Vyper_MB_CE_6.2#27]
Hi team, uploaded [this](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/blob/main/builds/main_board_LA_IS_7x7.bin)  firmware and screen firmware to my Anycubic Vyper. Everything seems to look ok, all calibration and screen operations works fine but when I initiate print from SD card after about 15 mins it seems that mainboard reboots, and printing stops and screen backs to the main scree.

Are there any logs I can check ? Is this a known issue ? Any suggestions ?

I tried to reflash firmware but issue remain the same. 

I will appreciate any suggestions.

Thanks, Paweł

**Comment by rommulaner** [comment]
Hello Pawel!
Sorry to disappoint you, but the TEAM is only me. 😃 
This normally happens, if the software is running into failures, like wrong commands in the gcode, read errors from the SD Card or commands that run into errors.

Does this also happen with a different SD card and known working gcode? And is it always after the same time printing?
What commands does the printer trying to run when the error occurs?

**Comment by rommulaner** [comment]
Watching the layer height an position where it is printing and then check the code in that area.
Normally such behavior happens when the card cannot be read or the gcode is faulty.

**Comment by Gman1988** [comment]
I reflash firmware as I noticed new release but it it still the same. At some point printing just stops and screen goes back to the initial state.  I will check at which layer it stops.

**Comment by rommulaner** [comment]
I had the same behavior during testing as the beeper wasn't configured correctly. When the printer tried to make a beep as written in the gcode it rebooted. But that was fixed.
Same occurres also on my new other printer (Kobra 2 Max) if I have Klipper commands in the gcode. This was because the slicer was set at gcode flavor to "Klipper".

**Comment by rommulaner** [comment]
Any news here?

**Comment by Gman1988** [comment]
Sorry I was away for a while, I will test this again.

sob., 9 mar 2024, 22:05 użytkownik Robert ***@***.***>
napisał:

**Comment by Mootfrost777** [comment]
@rommulaner I notice the same behavior on temps above 180C. In logs there is Thermal runaway error. PID is calibrated.

Some related info: https://github.com/MarlinFirmware/Marlin/issues/5341

**Comment by rommulaner** [comment]
I think this has something to do with the auto fan reduction when the temp falls below the set temp. I have deactivated that because for me it makes more sense to have a proper cooling. I have no issues with that but I have a silicone sock installed what I hardly recommend. You don't have a silicone sock or?

**Comment by Gman1988** [comment]
Hi all.

Where to disable auto fan reduction?

What is silicone sock ?

niedz., 26 maj 2024, 12:36 użytkownik Robert ***@***.***>
napisał:

**Comment by rommulaner** [comment]
The auto fan reduction is already deactivated in the firmware. A silicone sock for the heatblock. Makes the temps on the Hotend more stable.

**Comment by rommulaner** [comment]
In the new release 6.2.2 are now compiled variant with Fan Slow Down (FSD) available. With this versions the fan speed will be reduced if the hotend temp falls below the set temp to keep up.
