### ISSUE TITLE
Temps and all instructions 

### ISSUE THREAD

**Issue by Loud88GT** [rommulaner/Anycubic_Vyper_MB_CE_6.2#33]
I'd like to see the ability to print at higher temps so I can finally print nylon. Also, as I'm not familiar with compiling the firmware, maybe some detailed instructions on how to do so. Thanks so much for all your hard work as it's made my Vyper usable again!

**Comment by rommulaner** [comment]
There are files ready to flash in the release. There are also versions for higher possible hotend temps.

**Comment by Loud88GT** [comment]
Sorry, I'm new to GitHub and navigating isn't self explanatory for me. Thanks for pointing out where these files are and thanks again for all your hard work on this firmware!
