### ISSUE TITLE
Z Homing

### ISSUE THREAD

**Issue by Gawper5** [rommulaner/Anycubic_Vyper_MB_CE_6.2#36]
Whenever i home Z, it gets wrong number example zOffset = -4.5, but when you start the print the nozzle start too low so i have to have zOffset = -2.5

**Comment by rommulaner** [comment]
What version do have on the printer and screen?

**Comment by Gawper5** [comment]
latest screen
printer LA IS 7x7 300°C

**Comment by rommulaner** [comment]
6.2.2 is the newest version, currently on Prerelease but is nearly similar to 6.2.1-4 what is the latest release.
Ok. How was the leveling done? 
Did you probe the base z-offset with the home button on the calibration screen before running the ABL?

**Comment by rommulaner** [comment]
That's the problem: 
1. Base Z-Offset probing 
2. start ABL

Otherwise you double the offset.
It's also written in the release notes of the screen and also on top of the calibration screen.

**Comment by Gawper5** [comment]
Looks like it work now. Thank you
