### ISSUE TITLE
Question about input shaping

### ISSUE THREAD

**Issue by GremlineQ** [rommulaner/Anycubic_Vyper_MB_CE_6.2#41]
I have no idea where to ask, so I'll ask here if it is allowed. As far as I know, this firmware is based on Marlin, and I just want to know how to connect accelerometers so that I can calibrate the input shaping, because from what I know, it could be connected to Raspberry Pi in Klipper, but how should they be connected in Marlin or the only option is to manualy calibrate? And is it worth calibrating input shaping in this printer?

**Comment by convicte** [comment]
https://marlinfw.org/docs/gcode/M593.html

More specifically:
![image](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/assets/78666770/af99b996-2e95-4e91-ab18-4745acdc6851)

**Comment by rommulaner** [comment]
Exactly like it's been written in the post above. You need to do a test print like you can read in the link.
