### ISSUE TITLE
firmware with enabled skew correction

### ISSUE THREAD

**Issue by GremlineQ** [rommulaner/Anycubic_Vyper_MB_CE_6.2#42]
I think that a good idea (if possible) would be to enable the skew correction function in the already prepared firmware files, especially now that califlower is free to download for a week, many people may be interested in it.

**Comment by rommulaner** [comment]
What should there be activated? I think it's active by default.

**Comment by GremlineQ** [comment]
> What should there be activated? I think it's active by default. 

from what I know so far, the command for skew correction is m852 in the console, when I tried to use it, the output of this command was an unknown command

**Comment by rommulaner** [comment]
Ah, I see, it's deactivated...
What is there a sufficient way to configure it? ![image](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/assets/101675088/0a267606-0def-4099-8fbf-26a02ba6eb3c)
Any suggestions?

**Comment by GremlineQ** [comment]
ok, sorry for the trouble, I thought that it would be enough to turn it on, but from what I see, the values that will be calculated from the test must already be entered there (i.e. they may be different for each printer), so probably people who would like to have this skew correction would have to build the firmware themselves

**Comment by rommulaner** [comment]
What I just read about the califlower it works with the factors. So it's easy to enable and set the factors to zero and also enable the M-command. 
I can compile a version for you to test it. What variant do you need? 4x4 with stock Hotend and FSD?

**Comment by GremlineQ** [comment]
1) I use 4x4 with fullmetal hotend 
2) thang (just now I saw that this promotion has ended (if you want I can send you the filles))

**Comment by convicte** [comment]
Two words - intellectual property!

**Comment by rommulaner** [comment]
Here the 4x4 AllMetalHotend with activated skew.
Please test and give me feedback if it works as it should.
[main_board_LA_IS_4x4_AllMetalHotend_SKEW.zip](https://github.com/user-attachments/files/16071911/main_board_LA_IS_4x4_AllMetalHotend_SKEW.zip)

**Comment by GremlineQ** [comment]
works without any problems
