### ISSUE TITLE
Filament sensor

### ISSUE THREAD

**Issue by Gawper5** [rommulaner/Anycubic_Vyper_MB_CE_6.2#44]
Whenever the setting is turned on its like i doesnt detect it and always ejects filament.

**Comment by rommulaner** [comment]
Then it seems that your sensor is defect or the cable is not connected.

**Comment by Gawper5** [comment]
i know it worked on some older versions

**Comment by Gawper5** [comment]
Looks like its somehow damaged after like no use. Need to open it to further check
